version: '2'

services:
    wordpress:
        image: wordpress:latest
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_PASSWORD: example
        volumes:
            - .:/var/www/html/wp-content/plugins/jumplead/

    mysql:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: example
